#ifndef DEBUG_H
#define DEBUG_H

// デバッグ言語設定
enum class DebugLanguage { ENGLISH, JAPANESE };

// デバッグメッセージID
enum class DebugMsgId {
    // ノード作成関連
    NODE_CREATE_STMTLIST,
    NODE_CREATE_TYPESPEC,
    NODE_CREATE_VAR_DECL,
    NODE_CREATE_ASSIGN,
    NODE_CREATE_ARRAY_DECL,
    NODE_CREATE_FUNC_DECL,

    // 関数定義関連
    FUNC_DECL_REGISTER,
    FUNC_DECL_REGISTER_COMPLETE,
    PARAM_LIST_START,
    PARAM_LIST_SIZE,
    PARAM_LIST_COMPLETE,
    PARAM_LIST_DELETE,
    PARAM_LIST_NONE,
    FUNC_BODY_START,
    FUNC_BODY_EXISTS,
    FUNC_BODY_SET_COMPLETE,
    FUNC_BODY_NONE,
    FUNC_DEF_COMPLETE,

    // インタープリター関連
    INTERPRETER_START,
    AST_IS_NULL,
    GLOBAL_DECL_START,
    GLOBAL_DECL_COMPLETE,
    MAIN_FUNC_SEARCH,
    MAIN_FUNC_FOUND,
    MAIN_FUNC_EXIT,

    // 式評価関連
    EXPR_EVAL_NUMBER,
    EXPR_EVAL_VAR_REF,
    VAR_VALUE,
    EXPR_EVAL_ARRAY_REF,
    ARRAY_INDEX,
    STRING_ELEMENT_ACCESS,
    STRING_LENGTH_UTF8,
    STRING_ELEMENT_VALUE,
    ARRAY_ELEMENT_ACCESS,
    ARRAY_ELEMENT_VALUE,
    EXPR_EVAL_BINARY_OP,
    BINARY_OP_VALUES,

    // メイン関数関連
    PARSING_START,
    AST_GENERATED,
    EXECUTION_COMPLETE,

    // 変数代入関連
    VAR_ASSIGN,
    VAR_CREATE_NEW,
    VAR_ASSIGN_READABLE,    // 人間が読みやすい形式
    STRING_ASSIGN_READABLE, // 文字列代入の読みやすい形式
    STRING_VAR_CREATE_NEW,  // 文字列変数作成

    // 配列初期化関連
    ARRAY_INIT_CALLED,
    ARRAY_INIT_WITH_TYPE_CALLED,
    ARRAY_LITERAL_CALLED,
    ARRAY_LITERAL_COMPLETED,
    ARRAY_INIT_COMPLETED,
    ARRAY_INIT_WITH_TYPE_COMPLETED,
    ARRAY_LITERAL_ELEMENTS,
    ARRAY_INIT_ELEMENTS,
    TYPE_MISMATCH_ARRAY_INIT,
    CURRENT_TYPE_SET,

    // エラーメッセージ
    PARSER_ERROR,
    TYPE_MISMATCH_ERROR,

    // 型システム関連
    TYPEDEF_REGISTER,
    TYPEDEF_REGISTER_SUCCESS,
    TYPE_ALIAS_RESOLVE,
    TYPE_ALIAS_CREATE_NODE,
    TYPE_ALIAS_RUNTIME_RESOLVE,
    TYPE_RESOLVING,
    TYPE_ALREADY_RESOLVED,

    // インタープリターエラー関連
    VAR_REDECLARE_ERROR,
    NEGATIVE_ARRAY_SIZE_ERROR,
    MAIN_FUNC_NOT_FOUND_ERROR,
    UNDEFINED_VAR_ERROR,
    DIRECT_ARRAY_REF_ERROR,
    UNDEFINED_ARRAY_ERROR,
    STRING_OUT_OF_BOUNDS_ERROR,
    ARRAY_OUT_OF_BOUNDS_ERROR,
    NON_ARRAY_REF_ERROR,
    ZERO_DIVISION_ERROR,
    UNKNOWN_BINARY_OP_ERROR,
    UNKNOWN_UNARY_OP_ERROR,
    UNDEFINED_FUNC_ERROR,
    ARG_COUNT_MISMATCH_ERROR,
    ARRAY_DECL_AS_EXPR_ERROR,
    UNSUPPORTED_EXPR_NODE_ERROR,
    CONST_REASSIGN_ERROR,
    DIRECT_ARRAY_ASSIGN_ERROR,
    CONST_ARRAY_ASSIGN_ERROR,
    CONST_STRING_ELEMENT_ASSIGN_ERROR,
    TYPE_RANGE_ERROR,
    NON_STRING_CHAR_ASSIGN_ERROR,

    // デバッグ情報
    STRING_LITERAL_DEBUG,
    BINARY_OP_RESULT_DEBUG,
    UNARY_OP_DEBUG,
    UNARY_OP_OPERAND_DEBUG,
    UNARY_OP_RESULT_DEBUG,
    EXISTING_VAR_ASSIGN_DEBUG,
    EXISTING_STRING_VAR_ASSIGN_DEBUG,
    STRING_ELEMENT_ASSIGN_DEBUG,
    STRING_LENGTH_UTF8_DEBUG,
    STRING_ELEMENT_REPLACE_DEBUG,
    STRING_AFTER_REPLACE_DEBUG,
    ARRAY_DECL_EVAL_DEBUG,

    // 新しい配列デバッグメッセージ
    VAR_DECLARATION_DEBUG,
    ARRAY_TYPEDEF_DETECTED_DEBUG,
    NORMAL_ARRAY_TYPE_DEBUG,
    ARRAY_SIZE_DEBUG,
    ARRAY_LITERAL_ASSIGN_DEBUG,

    // 意味解析デバッグメッセージ
    DEBUG_SEMANTIC_ANALYSIS_START,
    DEBUG_SEMANTIC_ANALYSIS_COMPLETE,
    DEBUG_TYPEDEF_SEMANTIC_ANALYSIS,
    DEBUG_TYPEDEF_REGISTERED,
    DEBUG_ARRAY_TYPEDEF_REGISTERED,
    DEBUG_VAR_SEMANTIC_ANALYSIS,
    DEBUG_VAR_SEMANTIC_COMPLETE,
    DEBUG_ARRAY_LITERAL_VALIDATED,

    // 配列メモリ管理デバッグメッセージ
    ARRAY_ALLOC,
    ARRAY_CREATE,
    ARRAY_DESTROY,
};

// デバッグモードフラグ（外部宣言）
extern bool debug_mode;
extern DebugLanguage debug_language;

// デバッグ出力関数（既存）
void debug_print(const char *fmt, ...);

// 多言語対応デバッグ出力関数（新規）
void debug_msg(DebugMsgId msg_id, ...);

// 多言語対応エラー出力関数（新規）
void error_msg(DebugMsgId msg_id, ...);

#endif // DEBUG_H
