#ifndef DEBUG_H
#define DEBUG_H

// デバッグ言語設定
enum class DebugLanguage { ENGLISH, JAPANESE };

// デバッグメッセージID
enum class DebugMsgId {
    // ノード作成関連
    NODE_CREATE_STMTLIST,
    NODE_CREATE_TYPESPEC,
    NODE_CREATE_VAR_DECL,
    NODE_CREATE_ASSIGN,
    NODE_CREATE_ARRAY_DECL,
    NODE_CREATE_FUNC_DECL,

    // 関数定義関連
    FUNC_DECL_REGISTER,
    FUNC_DECL_REGISTER_COMPLETE,
    PARAM_LIST_START,
    PARAM_LIST_SIZE,
    PARAM_LIST_COMPLETE,
    PARAM_LIST_DELETE,
    PARAM_LIST_NONE,
    FUNC_BODY_START,
    FUNC_BODY_EXISTS,
    FUNC_BODY_SET_COMPLETE,
    FUNC_BODY_NONE,
    FUNC_DEF_COMPLETE,

    // インタープリター関連
    INTERPRETER_START,
    AST_IS_NULL,
    GLOBAL_DECL_START,
    GLOBAL_DECL_COMPLETE,
    MAIN_FUNC_SEARCH,
    MAIN_FUNC_FOUND,
    MAIN_FUNC_EXECUTE,
    MAIN_FUNC_BODY_EXISTS,
    MAIN_FUNC_BODY_NULL,
    MAIN_FUNC_EXIT,

    // 式評価関連
    EXPR_EVAL_NUMBER,
    EXPR_EVAL_VAR_REF,
    VAR_VALUE,
    EXPR_EVAL_ARRAY_REF,
    ARRAY_INDEX,
    STRING_ELEMENT_ACCESS,
    STRING_LENGTH_UTF8,
    STRING_ELEMENT_VALUE,
    ARRAY_ELEMENT_ACCESS,
    ARRAY_ELEMENT_VALUE,
    EXPR_EVAL_BINARY_OP,
    BINARY_OP_VALUES,

    // メイン関数関連
    PARSING_START,
    AST_GENERATED,
    EXECUTION_COMPLETE,

    // 変数代入関連
    VAR_ASSIGN,
    VAR_CREATE_NEW,
    VAR_ASSIGN_READABLE,    // 人間が読みやすい形式
    STRING_ASSIGN_READABLE, // 文字列代入の読みやすい形式
    STRING_VAR_CREATE_NEW,  // 文字列変数作成
    VAR_DECLARATION_DEBUG,  // 変数宣言デバッグ

    // 配列初期化関連
    ARRAY_INIT_CALLED,
    ARRAY_INIT_WITH_TYPE_CALLED,
    ARRAY_LITERAL_CALLED,
    ARRAY_LITERAL_ASSIGN_DEBUG, // 配列リテラル代入デバッグ
    ARRAY_LITERAL_COMPLETED,
    ARRAY_INIT_COMPLETED,
    ARRAY_INIT_WITH_TYPE_COMPLETED,
    ARRAY_LITERAL_ELEMENTS,
    ARRAY_INIT_ELEMENTS,
    TYPE_MISMATCH_ARRAY_INIT,
    CURRENT_TYPE_SET,

    // エラーメッセージ
    PARSER_ERROR,
    TYPE_MISMATCH_ERROR,

    // 型システム関連
    TYPEDEF_REGISTER,
    TYPEDEF_REGISTER_SUCCESS,
    TYPE_ALIAS_RESOLVE,
    TYPE_ALIAS_CREATE_NODE,
    TYPE_ALIAS_RUNTIME_RESOLVE,

    // インタープリターエラー関連
    VAR_REDECLARE_ERROR,
    NEGATIVE_ARRAY_SIZE_ERROR,
    DYNAMIC_ARRAY_NOT_SUPPORTED,
    MAIN_FUNC_NOT_FOUND_ERROR,
    UNDEFINED_VAR_ERROR,
    DIRECT_ARRAY_REF_ERROR,
    UNDEFINED_ARRAY_ERROR,
    STRING_OUT_OF_BOUNDS_ERROR,
    ARRAY_OUT_OF_BOUNDS_ERROR,
    NON_ARRAY_REF_ERROR,
    ZERO_DIVISION_ERROR,
    UNKNOWN_BINARY_OP_ERROR,
    UNKNOWN_UNARY_OP_ERROR,
    UNDEFINED_FUNC_ERROR,
    ARG_COUNT_MISMATCH_ERROR,
    ARRAY_DECL_AS_EXPR_ERROR,
    UNSUPPORTED_EXPR_NODE_ERROR,

    // 構造体・多次元配列関連（新規追加）
    PARSE_STRUCT_DEF,
    PARSE_VAR_DECL,
    PARSE_EXPR_ARRAY_ACCESS,
    INTERPRETER_EXEC_STMT,
    INTERPRETER_VAR_DECL,
    VAR_MANAGER_PROCESS,
    VAR_MANAGER_STRUCT_CREATE,
    VAR_MANAGER_MULTIDIM_FLAG,
    EXPR_EVAL_STRUCT_MEMBER,
    EXPR_EVAL_MULTIDIM_ACCESS,

    // インタープリターエラー関連（続き）
    CONST_REASSIGN_ERROR,
    DIRECT_ARRAY_ASSIGN_ERROR,
    CONST_ARRAY_ASSIGN_ERROR,
    CONST_STRING_ELEMENT_ASSIGN_ERROR,
    TYPE_RANGE_ERROR,
    NON_STRING_CHAR_ASSIGN_ERROR,

    // デバッグ情報
    STRING_LITERAL_DEBUG,
    BINARY_OP_RESULT_DEBUG,
    UNARY_OP_DEBUG,
    UNARY_OP_OPERAND_DEBUG,
    UNARY_OP_RESULT_DEBUG,
    EXISTING_VAR_ASSIGN_DEBUG,
    EXISTING_STRING_VAR_ASSIGN_DEBUG,
    STRING_ELEMENT_ASSIGN_DEBUG,
    STRING_LENGTH_UTF8_DEBUG,
    STRING_ELEMENT_REPLACE_DEBUG,
    STRING_AFTER_REPLACE_DEBUG,
    ARRAY_DECL_EVAL_DEBUG,

    // 多次元配列関連
    ARRAY_DECL_DEBUG,
    ARRAY_DIMENSIONS_COUNT,
    MULTIDIM_ARRAY_PROCESSING,
    SINGLE_DIM_ARRAY_PROCESSING,
    MULTIDIM_ARRAY_ASSIGNMENT_DETECTED,
    MULTIDIM_ARRAY_ACCESS_INFO,
    FLAT_INDEX_CALCULATED,
    MULTIDIM_ARRAY_ASSIGNMENT_COMPLETED,
    ARRAY_ELEMENT_ASSIGN_DEBUG,
    VARIABLE_NOT_FOUND,
    ARRAY_INFO,
    ARRAY_INDEX_OUT_OF_BOUNDS,
    ARRAY_ELEMENT_ASSIGN_START,
    ARRAY_ELEMENT_ASSIGN_SUCCESS,

    // 配列宣言関連（追加）
    ARRAY_DECL_START,
    MULTIDIM_ARRAY_DECL_INFO,
    ARRAY_TOTAL_SIZE,
    MULTIDIM_ARRAY_DECL_SUCCESS,
    ARRAY_DECL_SUCCESS,
    ARRAY_DECL_COMPLETE_DEBUG,
    MULTIDIM_ARRAY_DECL_COMPLETE_DEBUG,

    // printf出力関連デバッグ
    PRINTF_OFFSET_CALLED,
    PRINTF_ARG_LIST_INFO,
    PRINTF_ARG_PROCESSING,
    PRINTF_ARRAY_REF_DEBUG,

    // 配列リテラル処理詳細メッセージ（新規追加）
    ARRAY_LITERAL_INIT_PROCESSING,
    ARRAY_ELEMENT_PROCESSING_DEBUG,
    ARRAY_ELEMENT_EVAL_START,
    ARRAY_ELEMENT_EVAL_VALUE,
    PRINT_MULTIPLE_PROCESSING,
    PRINT_SINGLE_ARG_DEBUG,
    PRINT_PRINTF_FORMAT_FOUND,
    PRINT_NO_ARGUMENTS_DEBUG,
    PRINT_EXECUTING_STATEMENT,
    PRINT_STATEMENT_HAS_ARGS,
    PRINT_CHECKING_ARGUMENT,
    PRINT_FOUND_STRING_LITERAL,
    PRINT_FORMAT_SPEC_CHECKING,
    PRINT_NO_FORMAT_SPECIFIERS,

    // 追加のメッセージID
    PARSE_CURRENT_TOKEN,
    PRINT_NO_ARGUMENTS,
    INTERPRETER_RETURN_ARRAY,

    // 新しいメッセージID
    PARSE_ENUM_DEF,
    INTERPRETER_RETURN_STMT,
    INTERPRETER_RETURN_VAR,
    INTERPRETER_RETURN_ARRAY_VAR,
    INTERPRETER_MULTIDIM_ARRAY_SIZE,
    INTERPRETER_REGULAR_ARRAY_SIZE,
    INTERPRETER_MULTIDIM_PROCESSING,
    INTERPRETER_MULTIDIM_ELEMENT,
    INTERPRETER_ARRAY_ELEMENT,
    INTERPRETER_RETURN_EXCEPTION,
    INTERPRETER_VAR_NOT_FOUND,
    PARSE_FUNCTION_CREATED,
    OUTPUT_FORMAT_SPEC_FOUND,
    OUTPUT_FORMAT_COUNT,

    // パーサー関連の新規メッセージID
    PARSE_USING_RECURSIVE_PARSER,
    PARSE_TYPE_CHECK,
    PARSE_REGISTER_GLOBAL_DECL,
    PARSE_STRUCT_REGISTER,
    PARSE_STRUCT_MEMBER_ARRAY,
    PARSE_STRUCT_MEMBER_REGULAR,
    PARSE_ENUM_REGISTER,
    PARSE_PROGRAM_START,
    PARSE_STATEMENT_START,
    PARSE_STATEMENT_SUCCESS,
    PARSE_PROGRAM_COMPLETE,
    PARSE_STATIC_MODIFIER,
    PARSE_CONST_MODIFIER,
    PARSE_TYPEDEF_START,
    PARSE_STRUCT_DECL_START,
    PARSE_ENUM_DECL_START,
    PARSE_TYPEDEF_OR_STRUCT_TYPE_FOUND,
    PARSE_IDENTIFIER_AFTER_TYPE,
    PARSE_FUNCTION_DETECTED,
    PARSE_ARRAY_DETECTED,
    PARSE_FUNCTION_DECL_FOUND,
    PARSE_STRUCT_VAR_DECL_FOUND,
    PARSE_STRUCT_ARRAY_DECL,
    PARSE_STRUCT_ARRAY_VAR_NAME,
    INTERPRETER_GLOBAL_VAR_INIT,
    INTERPRETER_EXCEPTION_IN_VAR_DECL,
    STRUCT_DEF_STORE,
    STRUCT_VAR_CREATE,
    STRUCT_MULTIDIM_ARRAY_CREATE,
    STRUCT_ARRAY_MEMBER_CREATE,
    STRUCT_REGULAR_MEMBER_CREATE,
    EXPRESSION_EVAL_ERROR,
    VARIABLE_ACCESS_ERROR,
    EXPR_EVAL_ARRAY_REF_START,
    EXPR_EVAL_CONDITION_FAILED,

    // 変数管理関連のメッセージID
    VAR_MANAGER_TYPE_RESOLVED,
    VAR_MANAGER_STRUCT_VAR_CREATE,
    VAR_MANAGER_MULTIDIM_MEMBER_CREATE,
    VAR_MANAGER_ARRAY_MEMBER_INIT,
    VAR_MANAGER_MEMBER_ADDED,

    // インタープリター構造体関連のメッセージID
    INTERPRETER_STRUCT_ARRAY_MEMBER_ADDED,
    INTERPRETER_ARRAY_DIMENSION_INFO,
    INTERPRETER_STRUCT_MEMBER_ADDED,
    INTERPRETER_STRUCT_REGISTERED,
    INTERPRETER_ENUM_REGISTERING,
    INTERPRETER_MULTIPLE_VAR_DECL_START,
    INTERPRETER_GLOBAL_VAR_INIT_START,
    INTERPRETER_ARRAY_LITERAL_INIT,
    INTERPRETER_NORMAL_VAR_INIT,
    INTERPRETER_GET_STRUCT_MEMBER,
    INTERPRETER_VAR_NOT_STRUCT,
    INTERPRETER_STRUCT_MEMBERS_FOUND,
    INTERPRETER_STRUCT_MEMBER_FOUND,
    INTERPRETER_NAMED_STRUCT_LITERAL_INIT,
    INTERPRETER_MEMBER_INIT_PROCESSING,
    INTERPRETER_VAR_PROCESS_EXCEPTION,
    INTERPRETER_STRUCT_SYNCED,
    INTERPRETER_STRUCT_DEFINITION_STORED,
    INTERPRETER_SYNC_STRUCT_MEMBERS_START,
    INTERPRETER_SYNC_STRUCT_MEMBERS_END,
    INTERPRETER_PROCESSING_STMT_LIST,
    INTERPRETER_CHECKING_STATEMENT_TYPE,
    INTERPRETER_FOUND_VAR_DECL,

    // インタープリター実行関連のメッセージID
    INTERPRETER_STMT_DETAILS,
    INTERPRETER_STMT_LIST_EXEC,
    INTERPRETER_COMPOUND_STMT_EXEC,
    INTERPRETER_VAR_DECL_TYPE,
    INTERPRETER_VAR_DECL_SUCCESS,
    INTERPRETER_ASSIGNMENT,
    INTERPRETER_ASSIGNMENT_SUCCESS,
    INTERPRETER_MULTIPLE_VAR_DECL_EXEC,
    INTERPRETER_ARRAY_DECL_EXEC,
    INTERPRETER_IF_STMT_START,
    INTERPRETER_IF_CONDITION_RESULT,
    INTERPRETER_IF_THEN_EXEC,
    INTERPRETER_IF_ELSE_EXEC,
    INTERPRETER_IF_STMT_END,
    INTERPRETER_WHILE_STMT_START,
    INTERPRETER_WHILE_CONDITION_CHECK,
    INTERPRETER_WHILE_CONDITION_RESULT,
    INTERPRETER_WHILE_BODY_EXEC,
    INTERPRETER_WHILE_BREAK,
    INTERPRETER_WHILE_STMT_END,
    INTERPRETER_FOR_STMT_START,
    INTERPRETER_FOR_INIT_EXEC,
    INTERPRETER_FOR_CONDITION_CHECK,
    INTERPRETER_FOR_CONDITION_RESULT,
    INTERPRETER_FOR_BODY_EXEC,
    INTERPRETER_FOR_CONTINUE,
    INTERPRETER_FOR_UPDATE_EXEC,

    // 式評価関連のメッセージID
    EXPR_EVAL_START,
    EXPR_EVAL_STRING_LITERAL,
    EXPR_EVAL_VAR_NOT_FOUND,
    EXPR_EVAL_VAR_VALUE,
    EXPR_EVAL_MULTIDIM_MEMBER_ARRAY_ACCESS,
    EXPR_EVAL_MEMBER_ACCESS_DETAILS,
    EXPR_EVAL_ARRAY_INDEX,

    // 多次元文字列配列アクセス関連
    MULTIDIM_STRING_ARRAY_ACCESS,
    MULTIDIM_STRING_ARRAY_INDICES,
    MULTIDIM_STRING_ARRAY_VALUE,

    // printf処理関連
    PRINTF_PROCESSING_ARRAY_REF,
    PRINTF_ARRAY_NAME_FOUND,
    PRINTF_VARIABLE_FOUND,
    PRINTF_STRING_MULTIDIM_PROCESSING,
    PRINTF_STRING_VALUE_RETRIEVED,

    // interface/impl関連
    INTERFACE_DECL_START,
    INTERFACE_DECL_COMPLETE,
    INTERFACE_METHOD_FOUND,
    IMPL_DECL_START,
    IMPL_DECL_COMPLETE,
    IMPL_METHOD_REGISTER,
    IMPL_METHOD_REGISTER_COMPLETE,
    METHOD_CALL_START,
    METHOD_CALL_RECEIVER_FOUND,
    METHOD_CALL_INTERFACE,
    METHOD_CALL_CHAIN,      // メソッドチェーン処理開始
    METHOD_CALL_CHAIN_TEMP, // 一時変数作成
    METHOD_CALL_SELF_CONTEXT_SET,
    METHOD_CALL_SELF_MEMBER_SETUP,
    METHOD_CALL_EXECUTE,
    SELF_MEMBER_ACCESS_START,
    SELF_MEMBER_ACCESS_FOUND,
    SELF_MEMBER_ACCESS_VALUE,

    // interface変数代入関連
    INTERFACE_VARIABLE_ASSIGN,

    // 三項演算子型推論関連
    TERNARY_EVAL_START,
    TERNARY_NODE_TYPE,
    TERNARY_TYPE_INFERENCE,
    TERNARY_STRING_MEMBER_ACCESS,
    TERNARY_NUMERIC_EVAL,
    TERNARY_STRING_EVAL,

    // 三項演算子変数初期化関連
    TERNARY_VAR_INIT_START,
    TERNARY_VAR_CONDITION,
    TERNARY_VAR_BRANCH_TYPE,
    TERNARY_VAR_STRING_SET,
    TERNARY_VAR_NUMERIC_SET,

    MAX_DEBUG_MSG_ID // 最大値マーカー
};

// デバッグモードフラグ（外部宣言）
extern bool debug_mode;
extern DebugLanguage debug_language;

// デバッグ出力関数（既存）
void debug_print(const char *fmt, ...);

// 多言語対応デバッグ出力関数（新規）
void debug_msg(DebugMsgId msg_id, ...);

// 多言語対応エラー出力関数（新規）
void error_msg(DebugMsgId msg_id, ...);

#endif // DEBUG_H
